### ISSUE TITLE
-p and -a options do not work

### ISSUE THREAD

**Issue by MartonSzoboszlay** [TTloveTT/PhyloCore#1]
Hello,

I'm trying to run PhyloCore on a Linux machine with Ubuntu 16.04.1. I noticed that whenever I specify a -p or -a value in the script, I get an empty table as a result (just the first row with the sample names, no OTUs listed) regardless whether I use a phylogenetic tree, or not, or whether I use my own data, or the example dataset from Caporaso et al. included in PhyloCore.
Best,

Marton

**Comment by TTloveTT** [comment]
Hi Marton,

Thanks for letting me know. Which version of PhyloCore did you use? The
perl version or the python version? Could you send the exact command you
used?


Best,
Tiantian

**Comment by MartonSzoboszlay** [comment]
Hello Tiantian,

Thanks for your reply! I used the python version.
This command works:
python /opt/PhyloCore/PhyloCore.py -i /opt/PhyloCore/test/Caporaso_otu_table_taxon.txt -o Caporaso_test_results.txt
This does not:
python /opt/PhyloCore/PhyloCore.py -i /opt/PhyloCore/test/Caporaso_otu_table_taxon.txt -o Caporaso_test_results_2.txt -p 0.1
It doesn't seem to matter what p-value I use, I get an empty table as a result. The same thing happens if I specify an a-value.
Best,

Marton

**Comment by TTloveTT** [comment]
Hi Marton,

Sorry for the trouble. I will test it today and let you know. 

Best,
Tiantian

**Comment by TTloveTT** [comment]
Hi Marton,

I have fixed the bug. Python reads the argument as string not numeric values and causing the issue. Thank you for reporting this to me. Good luck with your work!


Best,
Tiantian
